"""Page 4 — model performance and global SHAP drivers (pre-rendered by Phases 1-2)."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import streamlit as st

from app_lib.common import ensure_state
from src.config import FIGURES_DIR, METRICS_PATH

st.set_page_config(page_title="Global Insights", page_icon="\U0001F30D", layout="wide")
ensure_state()

st.title("\U0001F30D Global model insights")

metrics = json.loads(METRICS_PATH.read_text())
xgb = metrics["models"]["xgboost"]["test"]
lr = metrics["models"]["logistic_regression"]["test"]

st.subheader("Model performance — hold-out test set")
c1, c2, c3, c4 = st.columns(4)
c1.metric("ROC-AUC", f"{xgb['roc_auc']:.3f}", help=f"LogisticRegression: {lr['roc_auc']:.3f}")
c2.metric("PR-AUC", f"{xgb['pr_auc']:.3f}", help=f"LogisticRegression: {lr['pr_auc']:.3f}")
c3.metric("Recall (defaulters caught)", f"{xgb['recall']:.0%}")
c4.metric("Precision (denied who'd default)", f"{xgb['precision']:.0%}")

p1, p2, p3 = st.columns(3)
p1.image(str(FIGURES_DIR / "roc_curve.png"), use_column_width=True)
p2.image(str(FIGURES_DIR / "pr_curve.png"), use_column_width=True)
p3.image(str(FIGURES_DIR / "confusion_matrix.png"), use_column_width=True)

st.divider()
st.subheader("What drives the model globally")
g1, g2 = st.columns(2)
g1.image(
    str(FIGURES_DIR / "shap_global_importance.png"),
    caption="Mean |SHAP| per original feature — checking_status dominates.",
    use_column_width=True,
)
g2.image(
    str(FIGURES_DIR / "shap_beeswarm.png"),
    caption="SHAP beeswarm on the transformed (one-hot) columns.",
    use_column_width=True,
)

st.subheader("Dependence — how the top numeric drivers behave")
d1, d2, d3 = st.columns(3)
for col, feat in zip((d1, d2, d3), ("duration_months", "credit_amount", "installment_rate_pct")):
    path = FIGURES_DIR / f"shap_dependence_{feat}.png"
    if path.exists():
        col.image(str(path), use_column_width=True)

st.caption(
    "Figures are generated by `python -m src.train` (Phase 1) and `python -m src.explain` "
    "(Phase 2); re-run those after retraining to refresh them here. Phase 4 adds a "
    "fairness breakdown by sex / age group / foreign-worker status."
)
